package com.dazz.backend.domain.musician;

import com.dazz.backend.domain.musician.exception.MusicianAlreadyClaimedException;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.*;

@DisplayName("Musician 도메인 단위 테스트")
class MusicianTest {

    @Test
    @DisplayName("신규 뮤지션은 userId가 없으므로 isClaimed()가 false다")
    void isClaimed_returnsFalse_whenUserIdIsNull() {
        // Given
        Musician musician = Musician.builder()
                .stageName("김재즈")
                .position(Position.PIANO)
                .build();

        // When & Then
        assertThat(musician.isClaimed()).isFalse();
    }

    @Test
    @DisplayName("claim() 호출 시 새 Musician에 userId가 연결되고 verificationTier가 UNVERIFIED로 바뀐다")
    void claim_success() {
        // Given
        Musician musician = Musician.builder()
                .stageName("김재즈")
                .position(Position.PIANO)
                .build();
        Long userId = 42L;

        // When
        Musician claimed = musician.claim(userId);

        // Then
        assertThat(claimed.getUserId()).isEqualTo(userId);
        assertThat(claimed.isClaimed()).isTrue();
        assertThat(claimed.getVerificationTier()).isEqualTo(VerificationTier.UNVERIFIED);
        // 원본 객체는 변하지 않는다 (불변 객체)
        assertThat(musician.isClaimed()).isFalse();
    }

    @Test
    @DisplayName("이미 claim된 뮤지션에 다시 claim하면 MusicianAlreadyClaimedException이 발생한다")
    void claim_throwsException_whenAlreadyClaimed() {
        // Given: 이미 userId=1L로 claim된 뮤지션
        Musician musician = Musician.builder()
                .stageName("김재즈")
                .position(Position.PIANO)
                .build();
        Musician claimed = musician.claim(1L);

        // When & Then: 다시 claim 시도하면 예외 발생
        assertThatThrownBy(() -> claimed.claim(2L))
                .isInstanceOf(MusicianAlreadyClaimedException.class);
    }

    @Test
    @DisplayName("uuid를 명시하지 않으면 자동 생성된다")
    void uuid_isAutoGenerated_whenNotProvided() {
        // Given & When
        Musician musician = Musician.builder()
                .stageName("김재즈")
                .build();

        // Then
        assertThat(musician.getUuid()).isNotNull();
    }
}
